/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JoinRouteImport } from './routes/join'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as QaLayoutRouteImport } from './routes/qa-layout'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WhyRouteImport } from './routes/why'
import { Route as AuthenticatedConnectorsRouteImport } from './routes/_authenticated/connectors'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedOneOnOneRouteImport } from './routes/_authenticated/one-on-one'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedReflectRouteImport } from './routes/_authenticated/reflect'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated/work'
import { Route as AuthenticatedCoachingIndexRouteImport } from './routes/_authenticated/coaching.index'
import { Route as AuthenticatedEngagementsIdRouteImport } from './routes/_authenticated/engagements.$id'
import { Route as ApiMcpTokenRouteImport } from './routes/api/mcp.$token'
import { Route as AuthenticatedCoachingEngagementIdSubjectIdRouteImport } from './routes/_authenticated/coaching.$engagementId.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const QaLayoutRoute = QaLayoutRouteImport.update({
  id: '/qa-layout',
  path: '/qa-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConnectorsRoute = AuthenticatedConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOneOnOneRoute = AuthenticatedOneOnOneRouteImport.update({
  id: '/one-on-one',
  path: '/one-on-one',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReflectRoute = AuthenticatedReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachingIndexRoute =
  AuthenticatedCoachingIndexRouteImport.update({
    id: '/coaching/',
    path: '/coaching/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngagementsIdRoute =
  AuthenticatedEngagementsIdRouteImport.update({
    id: '/engagements/$id',
    path: '/engagements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiMcpTokenRoute = ApiMcpTokenRouteImport.update({
  id: '/api/mcp/$token',
  path: '/api/mcp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachingEngagementIdSubjectIdRoute =
  AuthenticatedCoachingEngagementIdSubjectIdRouteImport.update({
    id: '/coaching/$engagementId/$subjectId',
    path: '/coaching/$engagementId/$subjectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/qa-layout': typeof QaLayoutRoute
  '/trust': typeof TrustRoute
  '/why': typeof WhyRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/one-on-one': typeof AuthenticatedOneOnOneRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/reflect': typeof AuthenticatedReflectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/work': typeof AuthenticatedWorkRoute
  '/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/api/mcp/$token': typeof ApiMcpTokenRoute
  '/coaching/': typeof AuthenticatedCoachingIndexRoute
  '/coaching/$engagementId/$subjectId': typeof AuthenticatedCoachingEngagementIdSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/qa-layout': typeof QaLayoutRoute
  '/trust': typeof TrustRoute
  '/why': typeof WhyRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/one-on-one': typeof AuthenticatedOneOnOneRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/reflect': typeof AuthenticatedReflectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/work': typeof AuthenticatedWorkRoute
  '/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/api/mcp/$token': typeof ApiMcpTokenRoute
  '/coaching': typeof AuthenticatedCoachingIndexRoute
  '/coaching/$engagementId/$subjectId': typeof AuthenticatedCoachingEngagementIdSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/qa-layout': typeof QaLayoutRoute
  '/trust': typeof TrustRoute
  '/why': typeof WhyRoute
  '/_authenticated/connectors': typeof AuthenticatedConnectorsRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/one-on-one': typeof AuthenticatedOneOnOneRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/reflect': typeof AuthenticatedReflectRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/work': typeof AuthenticatedWorkRoute
  '/_authenticated/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/api/mcp/$token': typeof ApiMcpTokenRoute
  '/_authenticated/coaching/': typeof AuthenticatedCoachingIndexRoute
  '/_authenticated/coaching/$engagementId/$subjectId': typeof AuthenticatedCoachingEngagementIdSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join'
    | '/no-access'
    | '/onboarding'
    | '/qa-layout'
    | '/trust'
    | '/why'
    | '/connectors'
    | '/decisions'
    | '/members'
    | '/one-on-one'
    | '/overview'
    | '/reflect'
    | '/settings'
    | '/work'
    | '/engagements/$id'
    | '/api/mcp/$token'
    | '/coaching/'
    | '/coaching/$engagementId/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/no-access'
    | '/onboarding'
    | '/qa-layout'
    | '/trust'
    | '/why'
    | '/connectors'
    | '/decisions'
    | '/members'
    | '/one-on-one'
    | '/overview'
    | '/reflect'
    | '/settings'
    | '/work'
    | '/engagements/$id'
    | '/api/mcp/$token'
    | '/coaching'
    | '/coaching/$engagementId/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/join'
    | '/no-access'
    | '/onboarding'
    | '/qa-layout'
    | '/trust'
    | '/why'
    | '/_authenticated/connectors'
    | '/_authenticated/decisions'
    | '/_authenticated/members'
    | '/_authenticated/one-on-one'
    | '/_authenticated/overview'
    | '/_authenticated/reflect'
    | '/_authenticated/settings'
    | '/_authenticated/work'
    | '/_authenticated/engagements/$id'
    | '/api/mcp/$token'
    | '/_authenticated/coaching/'
    | '/_authenticated/coaching/$engagementId/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  NoAccessRoute: typeof NoAccessRoute
  OnboardingRoute: typeof OnboardingRoute
  QaLayoutRoute: typeof QaLayoutRoute
  TrustRoute: typeof TrustRoute
  WhyRoute: typeof WhyRoute
  ApiMcpTokenRoute: typeof ApiMcpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-layout': {
      id: '/qa-layout'
      path: '/qa-layout'
      fullPath: '/qa-layout'
      preLoaderRoute: typeof QaLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/connectors': {
      id: '/_authenticated/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AuthenticatedConnectorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/one-on-one': {
      id: '/_authenticated/one-on-one'
      path: '/one-on-one'
      fullPath: '/one-on-one'
      preLoaderRoute: typeof AuthenticatedOneOnOneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reflect': {
      id: '/_authenticated/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof AuthenticatedReflectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaching/': {
      id: '/_authenticated/coaching/'
      path: '/coaching'
      fullPath: '/coaching/'
      preLoaderRoute: typeof AuthenticatedCoachingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements/$id': {
      id: '/_authenticated/engagements/$id'
      path: '/engagements/$id'
      fullPath: '/engagements/$id'
      preLoaderRoute: typeof AuthenticatedEngagementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/mcp/$token': {
      id: '/api/mcp/$token'
      path: '/api/mcp/$token'
      fullPath: '/api/mcp/$token'
      preLoaderRoute: typeof ApiMcpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coaching/$engagementId/$subjectId': {
      id: '/_authenticated/coaching/$engagementId/$subjectId'
      path: '/coaching/$engagementId/$subjectId'
      fullPath: '/coaching/$engagementId/$subjectId'
      preLoaderRoute: typeof AuthenticatedCoachingEngagementIdSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectorsRoute: typeof AuthenticatedConnectorsRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedOneOnOneRoute: typeof AuthenticatedOneOnOneRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedReflectRoute: typeof AuthenticatedReflectRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRoute
  AuthenticatedEngagementsIdRoute: typeof AuthenticatedEngagementsIdRoute
  AuthenticatedCoachingIndexRoute: typeof AuthenticatedCoachingIndexRoute
  AuthenticatedCoachingEngagementIdSubjectIdRoute: typeof AuthenticatedCoachingEngagementIdSubjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectorsRoute: AuthenticatedConnectorsRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedOneOnOneRoute: AuthenticatedOneOnOneRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedReflectRoute: AuthenticatedReflectRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkRoute: AuthenticatedWorkRoute,
  AuthenticatedEngagementsIdRoute: AuthenticatedEngagementsIdRoute,
  AuthenticatedCoachingIndexRoute: AuthenticatedCoachingIndexRoute,
  AuthenticatedCoachingEngagementIdSubjectIdRoute:
    AuthenticatedCoachingEngagementIdSubjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  NoAccessRoute: NoAccessRoute,
  OnboardingRoute: OnboardingRoute,
  QaLayoutRoute: QaLayoutRoute,
  TrustRoute: TrustRoute,
  WhyRoute: WhyRoute,
  ApiMcpTokenRoute: ApiMcpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
