/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JoinRouteImport } from './routes/join'
import { Route as NextRouteImport } from './routes/next'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WhyRouteImport } from './routes/why'
import { Route as AuthenticatedAiRecordRouteImport } from './routes/_authenticated/ai-record'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCoachNotesRouteImport } from './routes/_authenticated/coach-notes'
import { Route as AuthenticatedConnectorsRouteImport } from './routes/_authenticated/connectors'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedFirmRouteImport } from './routes/_authenticated/firm'
import { Route as AuthenticatedHowLassoWorksRouteImport } from './routes/_authenticated/how-lasso-works'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedOneOnOneRouteImport } from './routes/_authenticated/one-on-one'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedReflectRouteImport } from './routes/_authenticated/reflect'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated/work'
import { Route as JoinEduRouteImport } from './routes/join_.edu'
import { Route as AuthenticatedCoachingIndexRouteImport } from './routes/_authenticated/coaching.index'
import { Route as AuthenticatedDesignIconsRouteImport } from './routes/_authenticated/design.icons'
import { Route as AuthenticatedEngagementsIdRouteImport } from './routes/_authenticated/engagements.$id'
import { Route as ApiAnalysisStreamRouteImport } from './routes/api/analysis.stream'
import { Route as ApiCoachChatStreamRouteImport } from './routes/api/coach-chat.stream'
import { Route as ApiMcpTokenRouteImport } from './routes/api/mcp.$token'
import { Route as ApiReflectStreamRouteImport } from './routes/api/reflect.stream'
import { Route as AuthenticatedCoachingEngagementIdSubjectIdRouteImport } from './routes/_authenticated/coaching.$engagementId.$subjectId'
import { Route as ApiPublicHooksEgressSweepRouteImport } from './routes/api/public/hooks/egress-sweep'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const NextRoute = NextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiRecordRoute = AuthenticatedAiRecordRouteImport.update({
  id: '/ai-record',
  path: '/ai-record',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachNotesRoute = AuthenticatedCoachNotesRouteImport.update({
  id: '/coach-notes',
  path: '/coach-notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectorsRoute = AuthenticatedConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirmRoute = AuthenticatedFirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHowLassoWorksRoute =
  AuthenticatedHowLassoWorksRouteImport.update({
    id: '/how-lasso-works',
    path: '/how-lasso-works',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOneOnOneRoute = AuthenticatedOneOnOneRouteImport.update({
  id: '/one-on-one',
  path: '/one-on-one',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReflectRoute = AuthenticatedReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JoinEduRoute = JoinEduRouteImport.update({
  id: '/join_/edu',
  path: '/join/edu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachingIndexRoute =
  AuthenticatedCoachingIndexRouteImport.update({
    id: '/coaching/',
    path: '/coaching/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesignIconsRoute =
  AuthenticatedDesignIconsRouteImport.update({
    id: '/design/icons',
    path: '/design/icons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngagementsIdRoute =
  AuthenticatedEngagementsIdRouteImport.update({
    id: '/engagements/$id',
    path: '/engagements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAnalysisStreamRoute = ApiAnalysisStreamRouteImport.update({
  id: '/api/analysis/stream',
  path: '/api/analysis/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachChatStreamRoute = ApiCoachChatStreamRouteImport.update({
  id: '/api/coach-chat/stream',
  path: '/api/coach-chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpTokenRoute = ApiMcpTokenRouteImport.update({
  id: '/api/mcp/$token',
  path: '/api/mcp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReflectStreamRoute = ApiReflectStreamRouteImport.update({
  id: '/api/reflect/stream',
  path: '/api/reflect/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachingEngagementIdSubjectIdRoute =
  AuthenticatedCoachingEngagementIdSubjectIdRouteImport.update({
    id: '/coaching/$engagementId/$subjectId',
    path: '/coaching/$engagementId/$subjectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksEgressSweepRoute =
  ApiPublicHooksEgressSweepRouteImport.update({
    id: '/api/public/hooks/egress-sweep',
    path: '/api/public/hooks/egress-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/next': typeof NextRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/trust': typeof TrustRoute
  '/why': typeof WhyRoute
  '/ai-record': typeof AuthenticatedAiRecordRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/coach-notes': typeof AuthenticatedCoachNotesRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/firm': typeof AuthenticatedFirmRoute
  '/how-lasso-works': typeof AuthenticatedHowLassoWorksRoute
  '/members': typeof AuthenticatedMembersRoute
  '/one-on-one': typeof AuthenticatedOneOnOneRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reflect': typeof AuthenticatedReflectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/work': typeof AuthenticatedWorkRoute
  '/join/edu': typeof JoinEduRoute
  '/design/icons': typeof AuthenticatedDesignIconsRoute
  '/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/api/analysis/stream': typeof ApiAnalysisStreamRoute
  '/api/coach-chat/stream': typeof ApiCoachChatStreamRoute
  '/api/mcp/$token': typeof ApiMcpTokenRoute
  '/api/reflect/stream': typeof ApiReflectStreamRoute
  '/coaching/': typeof AuthenticatedCoachingIndexRoute
  '/coaching/$engagementId/$subjectId': typeof AuthenticatedCoachingEngagementIdSubjectIdRoute
  '/api/public/hooks/egress-sweep': typeof ApiPublicHooksEgressSweepRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/next': typeof NextRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/trust': typeof TrustRoute
  '/why': typeof WhyRoute
  '/ai-record': typeof AuthenticatedAiRecordRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/coach-notes': typeof AuthenticatedCoachNotesRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/firm': typeof AuthenticatedFirmRoute
  '/how-lasso-works': typeof AuthenticatedHowLassoWorksRoute
  '/members': typeof AuthenticatedMembersRoute
  '/one-on-one': typeof AuthenticatedOneOnOneRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reflect': typeof AuthenticatedReflectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/work': typeof AuthenticatedWorkRoute
  '/join/edu': typeof JoinEduRoute
  '/design/icons': typeof AuthenticatedDesignIconsRoute
  '/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/api/analysis/stream': typeof ApiAnalysisStreamRoute
  '/api/coach-chat/stream': typeof ApiCoachChatStreamRoute
  '/api/mcp/$token': typeof ApiMcpTokenRoute
  '/api/reflect/stream': typeof ApiReflectStreamRoute
  '/coaching': typeof AuthenticatedCoachingIndexRoute
  '/coaching/$engagementId/$subjectId': typeof AuthenticatedCoachingEngagementIdSubjectIdRoute
  '/api/public/hooks/egress-sweep': typeof ApiPublicHooksEgressSweepRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/next': typeof NextRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/trust': typeof TrustRoute
  '/why': typeof WhyRoute
  '/_authenticated/ai-record': typeof AuthenticatedAiRecordRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/coach-notes': typeof AuthenticatedCoachNotesRoute
  '/_authenticated/connectors': typeof AuthenticatedConnectorsRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/firm': typeof AuthenticatedFirmRoute
  '/_authenticated/how-lasso-works': typeof AuthenticatedHowLassoWorksRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/one-on-one': typeof AuthenticatedOneOnOneRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reflect': typeof AuthenticatedReflectRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/work': typeof AuthenticatedWorkRoute
  '/join_/edu': typeof JoinEduRoute
  '/_authenticated/design/icons': typeof AuthenticatedDesignIconsRoute
  '/_authenticated/engagements/$id': typeof AuthenticatedEngagementsIdRoute
  '/api/analysis/stream': typeof ApiAnalysisStreamRoute
  '/api/coach-chat/stream': typeof ApiCoachChatStreamRoute
  '/api/mcp/$token': typeof ApiMcpTokenRoute
  '/api/reflect/stream': typeof ApiReflectStreamRoute
  '/_authenticated/coaching/': typeof AuthenticatedCoachingIndexRoute
  '/_authenticated/coaching/$engagementId/$subjectId': typeof AuthenticatedCoachingEngagementIdSubjectIdRoute
  '/api/public/hooks/egress-sweep': typeof ApiPublicHooksEgressSweepRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join'
    | '/next'
    | '/no-access'
    | '/onboarding'
    | '/trust'
    | '/why'
    | '/ai-record'
    | '/archive'
    | '/assignments'
    | '/classes'
    | '/coach-notes'
    | '/connectors'
    | '/decisions'
    | '/firm'
    | '/how-lasso-works'
    | '/members'
    | '/one-on-one'
    | '/overview'
    | '/portfolio'
    | '/projects'
    | '/reflect'
    | '/settings'
    | '/work'
    | '/join/edu'
    | '/design/icons'
    | '/engagements/$id'
    | '/api/analysis/stream'
    | '/api/coach-chat/stream'
    | '/api/mcp/$token'
    | '/api/reflect/stream'
    | '/coaching/'
    | '/coaching/$engagementId/$subjectId'
    | '/api/public/hooks/egress-sweep'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/next'
    | '/no-access'
    | '/onboarding'
    | '/trust'
    | '/why'
    | '/ai-record'
    | '/archive'
    | '/assignments'
    | '/classes'
    | '/coach-notes'
    | '/connectors'
    | '/decisions'
    | '/firm'
    | '/how-lasso-works'
    | '/members'
    | '/one-on-one'
    | '/overview'
    | '/portfolio'
    | '/projects'
    | '/reflect'
    | '/settings'
    | '/work'
    | '/join/edu'
    | '/design/icons'
    | '/engagements/$id'
    | '/api/analysis/stream'
    | '/api/coach-chat/stream'
    | '/api/mcp/$token'
    | '/api/reflect/stream'
    | '/coaching'
    | '/coaching/$engagementId/$subjectId'
    | '/api/public/hooks/egress-sweep'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/join'
    | '/next'
    | '/no-access'
    | '/onboarding'
    | '/trust'
    | '/why'
    | '/_authenticated/ai-record'
    | '/_authenticated/archive'
    | '/_authenticated/assignments'
    | '/_authenticated/classes'
    | '/_authenticated/coach-notes'
    | '/_authenticated/connectors'
    | '/_authenticated/decisions'
    | '/_authenticated/firm'
    | '/_authenticated/how-lasso-works'
    | '/_authenticated/members'
    | '/_authenticated/one-on-one'
    | '/_authenticated/overview'
    | '/_authenticated/portfolio'
    | '/_authenticated/projects'
    | '/_authenticated/reflect'
    | '/_authenticated/settings'
    | '/_authenticated/work'
    | '/join_/edu'
    | '/_authenticated/design/icons'
    | '/_authenticated/engagements/$id'
    | '/api/analysis/stream'
    | '/api/coach-chat/stream'
    | '/api/mcp/$token'
    | '/api/reflect/stream'
    | '/_authenticated/coaching/'
    | '/_authenticated/coaching/$engagementId/$subjectId'
    | '/api/public/hooks/egress-sweep'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  NextRoute: typeof NextRoute
  NoAccessRoute: typeof NoAccessRoute
  OnboardingRoute: typeof OnboardingRoute
  TrustRoute: typeof TrustRoute
  WhyRoute: typeof WhyRoute
  JoinEduRoute: typeof JoinEduRoute
  ApiAnalysisStreamRoute: typeof ApiAnalysisStreamRoute
  ApiCoachChatStreamRoute: typeof ApiCoachChatStreamRoute
  ApiMcpTokenRoute: typeof ApiMcpTokenRoute
  ApiReflectStreamRoute: typeof ApiReflectStreamRoute
  ApiPublicHooksEgressSweepRoute: typeof ApiPublicHooksEgressSweepRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-record': {
      id: '/_authenticated/ai-record'
      path: '/ai-record'
      fullPath: '/ai-record'
      preLoaderRoute: typeof AuthenticatedAiRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach-notes': {
      id: '/_authenticated/coach-notes'
      path: '/coach-notes'
      fullPath: '/coach-notes'
      preLoaderRoute: typeof AuthenticatedCoachNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connectors': {
      id: '/_authenticated/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AuthenticatedConnectorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/firm': {
      id: '/_authenticated/firm'
      path: '/firm'
      fullPath: '/firm'
      preLoaderRoute: typeof AuthenticatedFirmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/how-lasso-works': {
      id: '/_authenticated/how-lasso-works'
      path: '/how-lasso-works'
      fullPath: '/how-lasso-works'
      preLoaderRoute: typeof AuthenticatedHowLassoWorksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/one-on-one': {
      id: '/_authenticated/one-on-one'
      path: '/one-on-one'
      fullPath: '/one-on-one'
      preLoaderRoute: typeof AuthenticatedOneOnOneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reflect': {
      id: '/_authenticated/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof AuthenticatedReflectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join_/edu': {
      id: '/join_/edu'
      path: '/join/edu'
      fullPath: '/join/edu'
      preLoaderRoute: typeof JoinEduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coaching/': {
      id: '/_authenticated/coaching/'
      path: '/coaching'
      fullPath: '/coaching/'
      preLoaderRoute: typeof AuthenticatedCoachingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design/icons': {
      id: '/_authenticated/design/icons'
      path: '/design/icons'
      fullPath: '/design/icons'
      preLoaderRoute: typeof AuthenticatedDesignIconsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engagements/$id': {
      id: '/_authenticated/engagements/$id'
      path: '/engagements/$id'
      fullPath: '/engagements/$id'
      preLoaderRoute: typeof AuthenticatedEngagementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/analysis/stream': {
      id: '/api/analysis/stream'
      path: '/api/analysis/stream'
      fullPath: '/api/analysis/stream'
      preLoaderRoute: typeof ApiAnalysisStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach-chat/stream': {
      id: '/api/coach-chat/stream'
      path: '/api/coach-chat/stream'
      fullPath: '/api/coach-chat/stream'
      preLoaderRoute: typeof ApiCoachChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/$token': {
      id: '/api/mcp/$token'
      path: '/api/mcp/$token'
      fullPath: '/api/mcp/$token'
      preLoaderRoute: typeof ApiMcpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reflect/stream': {
      id: '/api/reflect/stream'
      path: '/api/reflect/stream'
      fullPath: '/api/reflect/stream'
      preLoaderRoute: typeof ApiReflectStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coaching/$engagementId/$subjectId': {
      id: '/_authenticated/coaching/$engagementId/$subjectId'
      path: '/coaching/$engagementId/$subjectId'
      fullPath: '/coaching/$engagementId/$subjectId'
      preLoaderRoute: typeof AuthenticatedCoachingEngagementIdSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/egress-sweep': {
      id: '/api/public/hooks/egress-sweep'
      path: '/api/public/hooks/egress-sweep'
      fullPath: '/api/public/hooks/egress-sweep'
      preLoaderRoute: typeof ApiPublicHooksEgressSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRecordRoute: typeof AuthenticatedAiRecordRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedCoachNotesRoute: typeof AuthenticatedCoachNotesRoute
  AuthenticatedConnectorsRoute: typeof AuthenticatedConnectorsRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedFirmRoute: typeof AuthenticatedFirmRoute
  AuthenticatedHowLassoWorksRoute: typeof AuthenticatedHowLassoWorksRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedOneOnOneRoute: typeof AuthenticatedOneOnOneRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReflectRoute: typeof AuthenticatedReflectRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRoute
  AuthenticatedDesignIconsRoute: typeof AuthenticatedDesignIconsRoute
  AuthenticatedEngagementsIdRoute: typeof AuthenticatedEngagementsIdRoute
  AuthenticatedCoachingIndexRoute: typeof AuthenticatedCoachingIndexRoute
  AuthenticatedCoachingEngagementIdSubjectIdRoute: typeof AuthenticatedCoachingEngagementIdSubjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRecordRoute: AuthenticatedAiRecordRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedCoachNotesRoute: AuthenticatedCoachNotesRoute,
  AuthenticatedConnectorsRoute: AuthenticatedConnectorsRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedFirmRoute: AuthenticatedFirmRoute,
  AuthenticatedHowLassoWorksRoute: AuthenticatedHowLassoWorksRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedOneOnOneRoute: AuthenticatedOneOnOneRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReflectRoute: AuthenticatedReflectRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkRoute: AuthenticatedWorkRoute,
  AuthenticatedDesignIconsRoute: AuthenticatedDesignIconsRoute,
  AuthenticatedEngagementsIdRoute: AuthenticatedEngagementsIdRoute,
  AuthenticatedCoachingIndexRoute: AuthenticatedCoachingIndexRoute,
  AuthenticatedCoachingEngagementIdSubjectIdRoute:
    AuthenticatedCoachingEngagementIdSubjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  NextRoute: NextRoute,
  NoAccessRoute: NoAccessRoute,
  OnboardingRoute: OnboardingRoute,
  TrustRoute: TrustRoute,
  WhyRoute: WhyRoute,
  JoinEduRoute: JoinEduRoute,
  ApiAnalysisStreamRoute: ApiAnalysisStreamRoute,
  ApiCoachChatStreamRoute: ApiCoachChatStreamRoute,
  ApiMcpTokenRoute: ApiMcpTokenRoute,
  ApiReflectStreamRoute: ApiReflectStreamRoute,
  ApiPublicHooksEgressSweepRoute: ApiPublicHooksEgressSweepRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
