import { describe, expect, it } from "vitest";

import { brandForVendor } from "@/lib/tool-brand";
import {
  McpClientError,
  parseToolList,
  parseToolResult,
  resultJson,
} from "@/lib/mcp-client.server";
import { CONNECTOR_TOOLKITS } from "@/lib/connector-toolkits";
import { TOOL_VENDORS, vendorFromSource } from "@/lib/work-taxonomy";
import { mapMeetingDetail, mapMeetings, maskIdentity, meetingMarkdown, nextCursor } from "@/lib/wispr.server";

describe("pass166 mcp client", () => {
  it("reads a tools/list result", () => {
    const tools = parseToolList({
      tools: [
        { name: "list_meetings", description: "List meetings" },
        { name: "get_meeting" },
        { name: 7 },
      ],
    });
    expect(tools.map((t) => t.name)).toEqual(["list_meetings", "get_meeting"]);
    expect(tools[0]?.description).toBe("List meetings");
    expect(tools[1]?.description).toBeNull();
  });

  it("reads a tools/call result and its json payload", () => {
    const result = parseToolResult({
      content: [{ type: "text", text: '{"meetings":[]}' }],
    });
    expect(result.text).toBe('{"meetings":[]}');
    expect(result.isError).toBe(false);
    expect(resultJson(result)).toEqual({ meetings: [] });
  });

  it("degrades to a typed error on a malformed reply", () => {
    expect(() => parseToolList({ nope: true })).toThrowError(McpClientError);
    expect(() => parseToolResult({})).toThrowError(McpClientError);
    try {
      parseToolResult({});
    } catch (e) {
      expect((e as McpClientError).kind).toBe("protocol");
    }
  });
});

describe("pass166 wispr mapping", () => {
  const payload = {
    meetings: [
      {
        id: "m1",
        title: "Pricing call",
        start_time: "2026-08-01T10:00:00Z",
        attendees: [{ name: "A" }, { name: "B" }],
      },
      { title: "no id" },
    ],
    next_cursor: "abc",
  };

  it("lists meetings with title, date and attendee count", () => {
    const meetings = mapMeetings(payload);
    expect(meetings).toHaveLength(1);
    expect(meetings[0]).toMatchObject({
      id: "m1",
      title: "Pricing call",
      date: "2026-08-01T10:00:00Z",
      attendeeCount: 2,
    });
    expect(nextCursor(payload)).toBe("abc");
  });

  it("shapes a meeting the same way the Granola import does", () => {
    const detail = mapMeetingDetail({
      meeting: {
        id: "m1",
        title: "Pricing call",
        start_time: "2026-08-01T10:00:00Z",
        transcript: [{ speaker: "Ada", text: "Hello" }],
        summary: "They want a quote.",
      },
    });
    expect(detail?.markdown).toBe(
      "# Pricing call\n\n## Transcript\n\n**Ada:** Hello\n\n---\n\n## AI notes (generated by Wispr Flow)\n\nThey want a quote.",
    );
    expect(meetingMarkdown({ title: "T", transcript: null, summary: null, notes: null })).toBe("# T");
    expect(mapMeetingDetail({ meeting: { id: "m2", title: "Empty" } })).toBeNull();
  });

  it("shows only a masked account line", () => {
    expect(maskIdentity("ada@acme.com")).toBe("ad••••@acme.com");
    expect(maskIdentity(null)).toBeNull();
  });
});

describe("pass166 wispr identity", () => {
  it("is a known toolkit and vendor with its own mark", () => {
    expect(CONNECTOR_TOOLKITS).toContain("wispr");
    expect(TOOL_VENDORS).toContain("wispr");
    expect(vendorFromSource({ source: "connector:wispr" })).toBe("wispr");
    expect(brandForVendor("wispr")).toBe("wispr");
  });

  it("keeps meeting content out of every event dimension", async () => {
    const { readFileSync } = await import("node:fs");
    const src = readFileSync("src/lib/wispr.functions.ts", "utf8");
    const dims = src.match(/dims:\s*\{[^}]*\}/g) ?? [];
    expect(dims.length).toBeGreaterThan(0);
    for (const block of dims) {
      for (const word of ["title", "meeting_title", "attendee", "transcript", "url", "search"]) {
        expect(block).not.toContain(word);
      }
    }
  });
});
